### ISSUE TITLE
Hi the code is not working tried so many times below is the code

### ISSUE THREAD

**Issue by rohith231** [mschez/react-trip-animation#4]
hi  the code is not working check the attached text part link of my code   [Flight](https://drive.google.com/file/d/119kVkaBTF3GxbjCd1yMIRqdHw2Y2Jo2O/view?usp=sharing)

**Comment by mschez** [comment]
Hey, the problem is that you are trying to use this component in a (old) React Class component. This component is used using React Hooks, so it is not compatible with React Class.

**Comment by rohith231** [comment]
Hi, can u tell me the code &   how to implement using  react-hooks .

**Comment by rohith231** [comment]
Hi Here is the code using Hooks but still not working can u remodify and tell me where it is wrong[code](https://drive.google.com/file/d/1-WY1ZE_LHmp90DcCvXT_AOxLCIAbixto/view?usp=sharing)

**Comment by mschez** [comment]
Why you are using a Map component from react-leaflet? It is not necessary, please see the code in the demo folder.

Thanks
