### ISSUE TITLE
HI i am not understanding path.js code in the src can u explain it how did u implemented on ur own this plugin. How can i implement any other plugin in my own 

### ISSUE THREAD

**Issue by rohith231** [mschez/react-trip-animation#5]
HI i am not understanding path.js code in the src can u explain it how did u implemented on ur own this plugin.
 How can i implement any other plugin in my own can u tell me please

**Comment by mschez** [comment]
Hey, the code in Path.js is to draw the curve lines and the dotted shadows between two points. I implemented it reading the documentation from Leaflet. [Here](https://leafletjs.com/examples.html) and [here](https://leafletjs.com/plugins.html) you can found all the documentation and examples.

Thanks.
